spring.application.name=daenggo
spring.profiles.active=local

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false


#spring.web.resources.static-locations=classpath:/static/,file:./uploads/

spring.servlet.multipart.enabled=true

# Community image upload limit
spring.servlet.multipart.max-file-size=10MB
# 파일 외의 multipart 정보가 조금 추가되므로 요청 전체 크기는 여유를 둡니다.
spring.servlet.multipart.max-request-size=11MB


spring.web.resources.static-locations=classpath:/static/,file:./uploads/

auth.jwt.secret=${JWT_SECRET}
auth.jwt.issuer=${JWT_ISSUER:daenggo-api}
auth.jwt.access-token-expiration-seconds=${JWT_ACCESS_TOKEN_EXPIRATION_SECONDS:900}
